### ISSUE TITLE
Provide minified version

### ISSUE THREAD

**Issue by vvmnnnkv** [OpenMined/syft.js#210]
## Description
Provide minified version of JS dist file.

## Are you interested in working on this improvement yourself?
- Yes, I am.

## Additional Context
I tried to use `rollup-plugin-terser`, but this results in broken model tensors unserialization.
So it needs some more research why.

**Comment by shoniko** [comment]
I have tried to reproduce the issue from various angles, but everything seems to be working fine. I have tried stopping the training and then restoring from checkpoint and all seems fine. Perhaps the issue was fixed somewhere in dependencies? Added a PR to add minification here: https://github.com/OpenMined/syft.js/pull/235
